services:
  laravel-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: real_time_app
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379

  laravel-horizon:
    image: app_z-laravel-app
    container_name: laravel-horizon
    depends_on:
      - laravel-app
      - redis
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan horizon
    restart: always
    networks:
      - laravel-app-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  laravel-reverb-server:
    image: app_z-laravel-app
    container_name: reverb-server
    ports:
      - "8080:8080"
    depends_on:
      - laravel-app
    environment:
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: "172.16.0.219"
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-app-network
    command: php artisan reverb:start

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-app-network

  db:
    image: mysql:8.0
    container_name: laravel-app-db-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_z
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: laravel-app-nginx-container
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel-app-network

networks:
  laravel-app-network:
    driver: bridge

volumes:
  db-data:
